project_id: 456846
api_token: "apiToken" # secure problem?
base_path: "./" # optional
branch: "master" # optional
base_url: "https://api.crowdin.com" # optional (for Crowdin Enterprise only)
preserve_hierarchy: true

files:
  - source: locales/crowdin_test.json
    translation: /tranlocalesslation/%locale_with_underscore%.%file_extension%
